meta_product_name: "Orator Coach"
meta_title: "Orator Coach - The Public Speaking Coach"
meta_description: "Harness your fear of public speaking"
meta_image: "orator_logo_meta.png"
twitter_account: "@Lewagonparis"
